name: to_do_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  shared_preferences: ^2.5.3
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  go_router: ^15.1.2
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
